--liquibase formatted sql

--changeset migration:202603_16_1
create extension if not exists pg_trgm;

--changeset migration:202603_16_2
create table skill
(
    id              varchar(255) primary key,
    preferred_label varchar(255)             not null,
    alt_labels      text[]                   not null default '{}',
    description     text                     not null default '',
    tfidf_vector    double precision[],
    created_at      timestamp with time zone not null default now(),
    updated_at      timestamp with time zone not null default now()
);

--changeset migration:202603_16_3
create index idx_skill_preferred_label_trgm on skill using gin (preferred_label gin_trgm_ops);

--changeset migration:202603_16_4
create table module_preset
(
    id          uuid primary key,
    code        varchar(64)              not null unique,
    name        varchar(200)             not null,
    description text                     not null default '',
    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now()
);

--changeset migration:202603_16_5
create table module_skill
(
    module_id   uuid         not null references module_preset (id) on delete cascade,
    skill_id    varchar(255) not null references skill (id) on delete cascade,
    proficiency varchar(16)  not null,
    primary key (module_id, skill_id)
);

--changeset migration:202603_16_6
create index idx_module_skill_skill_id on module_skill (skill_id);

--changeset migration:202603_16_7
create table student_skill
(
    student_id  uuid                     not null references users (id) on delete cascade,
    skill_id    varchar(255)             not null references skill (id) on delete cascade,
    proficiency varchar(16)              not null,
    source      varchar(16)              not null,
    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now(),
    primary key (student_id, skill_id)
);

--changeset migration:202603_16_8
create index idx_student_skill_skill_id on student_skill (skill_id);

--changeset migration:202603_16_9
-- All ESCO IT skills seeded in a single statement (merged from what were
-- previously split across two later migrations). 235 rows total.
insert into skill (id, preferred_label, alt_labels, description) values
('esco/skill/java', 'Java', ARRAY['jdk','jvm','java se']::text[], 'General-purpose object-oriented programming language targeting the Java virtual machine, widely used for backend services, Android applications, and enterprise software.'),
('esco/skill/python', 'Python', ARRAY['python3','cpython']::text[], 'High-level dynamic programming language with rich standard library, popular for scripting, automation, data analysis, machine learning, and backend APIs.'),
('esco/skill/javascript', 'JavaScript', ARRAY['js','ecmascript']::text[], 'Dynamic scripting language of the web platform, executed in browsers and on servers, foundational for frontend development and Node.js backends.'),
('esco/skill/typescript', 'TypeScript', ARRAY['ts']::text[], 'Statically typed superset of JavaScript that compiles to plain JavaScript, used to build maintainable large-scale frontend and backend code bases.'),
('esco/skill/sql', 'SQL', ARRAY['structured query language','ansi sql']::text[], 'Declarative query language for relational databases, used to define schemas, retrieve data, and express joins, aggregations, and transactions.'),
('esco/skill/kotlin', 'Kotlin', ARRAY[]::text[], 'Statically typed JVM language with null-safety and coroutines, official language for Android application development and increasingly used on the server.'),
('esco/skill/swift', 'Swift', ARRAY[]::text[], 'Apple ecosystem programming language with strong type inference and memory safety, used to build iOS, iPadOS, and macOS applications.'),
('esco/skill/go', 'Go', ARRAY['golang']::text[], 'Compiled language designed for simplicity and concurrency via goroutines, common in cloud infrastructure, networking services, and command-line tools.'),
('esco/skill/rust', 'Rust', ARRAY[]::text[], 'Systems programming language with an ownership model that guarantees memory safety without a garbage collector, used for performance-critical services.'),
('esco/skill/c-plus-plus', 'C++', ARRAY['cpp']::text[], 'Compiled systems language with zero-cost abstractions, templates, and manual memory control, used in game engines, operating systems, and trading systems.'),
('esco/skill/object-oriented-programming', 'Object-Oriented Programming', ARRAY['oop']::text[], 'Programming paradigm based on classes, objects, encapsulation, inheritance, and polymorphism, applied to model domain concepts as software components.'),
('esco/skill/functional-programming', 'Functional Programming', ARRAY['fp']::text[], 'Programming paradigm emphasising pure functions, immutability, and higher-order functions, used to reason about transformations over data.'),
('esco/skill/git', 'Git', ARRAY['version control','vcs']::text[], 'Distributed version control system used to track source code history, manage branches, and collaborate through commits, merges, and pull requests.'),
('esco/skill/data-structures', 'Data Structures', ARRAY[]::text[], 'Fundamental arrangements of data such as arrays, lists, maps, trees, graphs, heaps, and hash tables, underpinning efficient algorithms and software design.'),
('esco/skill/algorithms', 'Algorithms', ARRAY[]::text[], 'Formal procedures for solving computational problems, including sorting, searching, graph traversal, dynamic programming, and greedy strategies.'),
('esco/skill/complexity-analysis', 'Algorithmic Complexity Analysis', ARRAY['big o','asymptotic analysis']::text[], 'Analytical reasoning about the time and space cost of algorithms, using big-O notation to compare scalability across input sizes.'),
('esco/skill/concurrency', 'Concurrency', ARRAY['multithreading','parallelism']::text[], 'Designing programs where multiple flows of control execute together, coordinating shared state with threads, tasks, locks, and asynchronous primitives.'),
('esco/skill/design-patterns', 'Software Design Patterns', ARRAY[]::text[], 'Reusable solutions to recurring design problems in object-oriented software, including creational, structural, and behavioural patterns.'),
('esco/skill/html', 'HTML', ARRAY['html5','markup']::text[], 'Markup language used to structure web pages, defining semantic elements, forms, and accessibility landmarks consumed by browsers and assistive technology.'),
('esco/skill/css', 'CSS', ARRAY['css3','styles']::text[], 'Style sheet language controlling the presentation of web documents, including layout, typography, responsive design, and animation.'),
('esco/skill/react', 'React', ARRAY['react.js','reactjs']::text[], 'Declarative JavaScript library for building component-based user interfaces, with hooks, virtual DOM diffing, and a large ecosystem of libraries.'),
('esco/skill/angular', 'Angular', ARRAY[]::text[], 'Opinionated TypeScript frontend framework with dependency injection, reactive forms, and RxJS observables for building enterprise single-page applications.'),
('esco/skill/nodejs', 'Node.js', ARRAY['node']::text[], 'JavaScript runtime built on the V8 engine, used to implement event-driven servers, APIs, and command-line tools using asynchronous I/O.'),
('esco/skill/rest-api', 'REST API Design', ARRAY['rest','restful services']::text[], 'Designing HTTP interfaces around resources, verbs, status codes, and content negotiation, following REST constraints for clients and servers.'),
('esco/skill/graphql', 'GraphQL', ARRAY[]::text[], 'Query language and runtime for APIs, allowing clients to request precisely the fields they need from a typed schema served over HTTP.'),
('esco/skill/spring-boot', 'Spring Boot', ARRAY['spring','spring framework']::text[], 'Java framework providing auto-configured building blocks for web services, data access, security, and messaging, backed by the Spring ecosystem.'),
('esco/skill/postgresql', 'PostgreSQL', ARRAY['postgres']::text[], 'Open-source relational database with advanced SQL features, JSON support, full-text search, and extensions such as pg_trgm and PostGIS.'),
('esco/skill/mysql', 'MySQL', ARRAY['mariadb']::text[], 'Widely used open-source relational database management system supporting transactions, replication, and standard SQL with MyISAM and InnoDB engines.'),
('esco/skill/mongodb', 'MongoDB', ARRAY['mongo']::text[], 'Document-oriented NoSQL database storing JSON-like BSON documents, supporting indexes, aggregation pipelines, and horizontal scaling via sharding.'),
('esco/skill/redis', 'Redis', ARRAY[]::text[], 'In-memory key-value data store used as a cache, message broker, and lightweight database, supporting lists, sets, streams, and pub/sub.'),
('esco/skill/database-design', 'Relational Database Design', ARRAY['data modelling','schema design']::text[], 'Designing normalized relational schemas, choosing keys and indexes, and modelling entity relationships to support performance and data integrity.'),
('esco/skill/orm', 'Object Relational Mapping', ARRAY['orm frameworks','hibernate','jpa']::text[], 'Mapping object-oriented domain models to relational tables using frameworks such as Hibernate and JPA, managing identity, associations, and transactions.'),
('esco/skill/machine-learning', 'Machine Learning', ARRAY['ml','supervised learning']::text[], 'Building statistical models that learn patterns from data, covering regression, classification, clustering, evaluation, and regularization.'),
('esco/skill/deep-learning', 'Deep Learning', ARRAY['neural networks']::text[], 'Training multi-layer neural networks with backpropagation, used for image recognition, natural language processing, and sequence modelling.'),
('esco/skill/pandas', 'pandas', ARRAY[]::text[], 'Python library offering DataFrame and Series structures for tabular data analysis, cleaning, joining, grouping, and time-series manipulation.'),
('esco/skill/numpy', 'NumPy', ARRAY[]::text[], 'Python library providing multi-dimensional arrays and vectorised numerical operations, the foundation of the scientific Python ecosystem.'),
('esco/skill/tensorflow', 'TensorFlow', ARRAY['tf','keras']::text[], 'Open-source deep learning framework with automatic differentiation, GPU acceleration, and a high-level Keras API for model building.'),
('esco/skill/data-analysis', 'Data Analysis', ARRAY['exploratory data analysis','eda']::text[], 'Cleaning, exploring, summarising, and visualising data sets to extract insight and to prepare features for downstream modelling.'),
('esco/skill/linux', 'Linux', ARRAY['unix','gnu/linux']::text[], 'Open-source Unix-like operating system family used on servers, workstations, and embedded devices, with command-line tooling and package managers.'),
('esco/skill/shell-scripting', 'Shell Scripting', ARRAY['bash','zsh']::text[], 'Automating command-line workflows using POSIX shell, Bash, or Zsh scripts, including pipelines, variables, conditionals, and loops.'),
('esco/skill/tcp-ip-networking', 'TCP/IP Networking', ARRAY['networking']::text[], 'Understanding the TCP/IP stack including IP addressing, routing, TCP and UDP transports, DNS, and common application-layer protocols.'),
('esco/skill/http-protocol', 'HTTP Protocol', ARRAY['http/2','http/3']::text[], 'Understanding HTTP methods, status codes, headers, caching semantics, connection management, and TLS, as the foundation of web communication.'),
('esco/skill/cryptography', 'Applied Cryptography', ARRAY['crypto']::text[], 'Using cryptographic primitives such as symmetric and asymmetric encryption, hashing, digital signatures, and key exchange to protect data.'),
('esco/skill/web-security', 'Web Application Security', ARRAY['owasp','appsec']::text[], 'Defending web applications against threats such as injection, cross-site scripting, CSRF, SSRF, and broken access control, aligned with the OWASP Top 10.'),
('esco/skill/authentication', 'Authentication and Authorization', ARRAY['authn','authz','oauth2','jwt']::text[], 'Verifying user identity and controlling resource access using OAuth2, OpenID Connect, JWT tokens, session cookies, and role-based access control.'),
('esco/skill/aws', 'Amazon Web Services', ARRAY['aws','amazon cloud']::text[], 'Public cloud platform providing EC2 compute, S3 object storage, RDS databases, IAM identity, and many managed services for building scalable systems.'),
('esco/skill/azure', 'Microsoft Azure', ARRAY['azure cloud']::text[], 'Microsoft public cloud platform providing virtual machines, App Service, Azure SQL, Active Directory, and managed Kubernetes offerings.'),
('esco/skill/docker', 'Docker', ARRAY['containers']::text[], 'Container platform used to package applications and their dependencies into images that run consistently across development, CI, and production environments.'),
('esco/skill/kubernetes', 'Kubernetes', ARRAY['k8s']::text[], 'Container orchestration platform for deploying, scaling, and operating containerised applications, using pods, deployments, services, and controllers.'),
('esco/skill/ci-cd', 'Continuous Integration and Delivery', ARRAY['ci','cd','devops pipelines']::text[], 'Automating build, test, and deployment pipelines so changes are integrated continuously and released to production on a reliable, repeatable cadence.'),
('esco/skill/terraform', 'Terraform', ARRAY['infrastructure as code','iac']::text[], 'Declarative infrastructure-as-code tool that provisions and manages cloud resources through HashiCorp Configuration Language and provider plugins.'),
('esco/skill/android-development', 'Android Application Development', ARRAY['android']::text[], 'Building mobile applications for the Android platform using Kotlin or Java, activities, fragments, Jetpack libraries, and the Android SDK.'),
('esco/skill/ios-development', 'iOS Application Development', ARRAY['ios']::text[], 'Building mobile applications for iOS using Swift, UIKit, and SwiftUI, targeting iPhone and iPad with the Apple developer toolchain.'),
('esco/skill/react-native', 'React Native', ARRAY[]::text[], 'Cross-platform mobile framework using React to build native Android and iOS applications that share most JavaScript or TypeScript code.'),
('esco/skill/figma', 'Figma', ARRAY[]::text[], 'Collaborative design tool used to produce user interface mockups, component libraries, and interactive prototypes for web and mobile applications.'),
('esco/skill/user-research', 'User Research', ARRAY['ux research']::text[], 'Interviewing users, running usability studies, synthesising findings, and translating insights into product and design decisions.'),
('esco/skill/accessibility', 'Accessibility (a11y)', ARRAY['a11y','wcag']::text[], 'Designing and building digital products that are usable by people with disabilities, aligned with WCAG guidelines and assistive technologies.'),
('esco/skill/unit-testing', 'Unit Testing', ARRAY['junit','pytest','jest']::text[], 'Writing automated tests that isolate individual units of code using frameworks such as JUnit, pytest, or Jest, with mocks, stubs, and assertions.'),
('esco/skill/integration-testing', 'Integration Testing', ARRAY[]::text[], 'Writing automated tests that exercise multiple collaborating components or services together, often using containerised databases and HTTP clients.'),
('esco/skill/test-driven-development', 'Test-Driven Development', ARRAY['tdd']::text[], 'Practice of writing a failing test before the code that satisfies it, then refactoring, in short red-green-refactor cycles.'),
('esco/skill/selenium', 'Selenium', ARRAY['webdriver']::text[], 'Browser automation toolkit used to write end-to-end tests that drive real browsers via the WebDriver protocol, frequently combined with Java or Python.'),
('esco/skill/distributed-systems', 'Distributed Systems', ARRAY[]::text[], 'Designing systems composed of networked nodes that coordinate to deliver reliability, availability, and scalability under partial failure.'),
('esco/skill/microservices', 'Microservices Architecture', ARRAY[]::text[], 'Architectural style that structures an application as a suite of independently deployable services communicating over lightweight protocols.'),
('esco/skill/aws-s3', 'AWS S3', ARRAY['s3','simple storage service']::text[], 'AWS object storage service for unstructured data with lifecycle, versioning, and IAM-based access policies.'),
('esco/skill/aws-ec2', 'AWS EC2', ARRAY['ec2','elastic compute cloud']::text[], 'AWS virtual machine service used to run Linux and Windows workloads with auto-scaling groups and security groups.'),
('esco/skill/aws-lambda', 'AWS Lambda', ARRAY['lambda','serverless']::text[], 'AWS serverless compute platform that runs code in response to events with per-millisecond billing.'),
('esco/skill/aws-iam', 'AWS IAM', ARRAY['iam','identity and access management']::text[], 'AWS identity service for users, roles, policies, and federated access governing every other AWS resource.'),
('esco/skill/aws-rds', 'AWS RDS', ARRAY['rds']::text[], 'Managed relational database service on AWS supporting Postgres, MySQL, MariaDB, Oracle, and SQL Server.'),
('esco/skill/aws-dynamodb', 'AWS DynamoDB', ARRAY['dynamodb']::text[], 'AWS fully managed key-value and document NoSQL database with single-digit-millisecond reads at any scale.'),
('esco/skill/aws-cloudfront', 'AWS CloudFront', ARRAY['cloudfront','cdn']::text[], 'AWS global content delivery network with edge caching, signed URLs, and Lambda@Edge integration.'),
('esco/skill/aws-sqs', 'AWS SQS', ARRAY['sqs','simple queue service']::text[], 'AWS managed message queue service with standard and FIFO queues for decoupling distributed components.'),
('esco/skill/aws-sns', 'AWS SNS', ARRAY['sns','simple notification service']::text[], 'AWS pub/sub messaging service for fan-out across SMS, email, HTTP, SQS, and Lambda subscribers.'),
('esco/skill/aws-ecs', 'AWS ECS', ARRAY['ecs','elastic container service']::text[], 'AWS container orchestration service running Docker containers on EC2 or Fargate.'),
('esco/skill/aws-eks', 'AWS EKS', ARRAY['eks','elastic kubernetes service']::text[], 'AWS managed Kubernetes service with control-plane SLA and IAM-integrated authentication.'),
('esco/skill/aws-cloudwatch', 'AWS CloudWatch', ARRAY['cloudwatch']::text[], 'AWS observability service for metrics, logs, alarms, and dashboards across native and custom sources.'),
('esco/skill/gcp', 'Google Cloud Platform', ARRAY['gcp','google cloud']::text[], 'Google public cloud platform offering Compute Engine, GKE, BigQuery, Pub/Sub, and Vertex AI.'),
('esco/skill/vue', 'Vue.js', ARRAY['vue','vue 3']::text[], 'Progressive JavaScript framework for building user interfaces with a reactive component model and SFC syntax.'),
('esco/skill/svelte', 'Svelte', ARRAY[]::text[], 'Compiled component framework that emits highly optimised vanilla JavaScript with reactive declarations.'),
('esco/skill/sveltekit', 'SvelteKit', ARRAY[]::text[], 'Full-stack Svelte framework with file-based routing, SSR, and server endpoints.'),
('esco/skill/astro', 'Astro', ARRAY[]::text[], 'Content-focused web framework with island architecture that ships zero JavaScript by default.'),
('esco/skill/solidjs', 'Solid.js', ARRAY['solid']::text[], 'Reactive JavaScript UI library with fine-grained reactivity compiled to imperative DOM updates.'),
('esco/skill/qwik', 'Qwik', ARRAY[]::text[], 'Resumable web framework that streams interactivity by serialising application state into HTML.'),
('esco/skill/remix', 'Remix', ARRAY[]::text[], 'Full-stack React framework built on web standards with nested routing and form-driven mutations.'),
('esco/skill/nextjs', 'Next.js', ARRAY['next']::text[], 'React framework offering file-system routing, SSR/SSG/ISR, server actions, and the App Router.'),
('esco/skill/nuxt', 'Nuxt', ARRAY[]::text[], 'Vue meta-framework providing SSR, file-based routing, modules, and server engine Nitro.'),
('esco/skill/tailwind', 'Tailwind CSS', ARRAY['tailwindcss']::text[], 'Utility-first CSS framework for rapidly composing custom designs without leaving HTML.'),
('esco/skill/pytorch', 'PyTorch', ARRAY['torch']::text[], 'Open-source deep learning library with eager execution, autograd, and a thriving research ecosystem.'),
('esco/skill/scikit-learn', 'scikit-learn', ARRAY['sklearn']::text[], 'Python machine learning library covering classification, regression, clustering, and model selection.'),
('esco/skill/huggingface', 'Hugging Face Transformers', ARRAY['transformers','huggingface']::text[], 'Library and hub for state-of-the-art transformer models for NLP, vision, and audio with a unified API.'),
('esco/skill/langchain', 'LangChain', ARRAY[]::text[], 'Python and JavaScript framework for composing LLM-backed applications with chains, tools, and agents.'),
('esco/skill/llamaindex', 'LlamaIndex', ARRAY[]::text[], 'Data framework for connecting LLMs to private and structured data via indexes and retrievers.'),
('esco/skill/jax', 'JAX', ARRAY[]::text[], 'NumPy-style numerical computing library with autodiff, JIT compilation, and accelerator support.'),
('esco/skill/ray', 'Ray', ARRAY[]::text[], 'Distributed compute framework for scaling Python ML workloads, with Tune, Train, and Serve libraries.'),
('esco/skill/llm-engineering', 'LLM Engineering', ARRAY['prompt engineering','retrieval augmented generation','rag']::text[], 'Designing prompts, retrieval pipelines, evaluation harnesses, and guardrails for production LLM systems.'),
('esco/skill/vector-db', 'Vector Databases', ARRAY['pinecone','weaviate','qdrant','milvus']::text[], 'Specialised stores for embeddings supporting approximate nearest neighbour search across high-dimensional vectors.'),
('esco/skill/mlops', 'MLOps', ARRAY['ml ops','model ops']::text[], 'Operational practices for training, packaging, deploying, monitoring, and rolling back machine learning models.'),
('esco/skill/prometheus', 'Prometheus', ARRAY[]::text[], 'Pull-based monitoring system with multi-dimensional metrics, PromQL, and a service-discovery scrape model.'),
('esco/skill/grafana', 'Grafana', ARRAY[]::text[], 'Open-source dashboarding platform that visualises metrics and logs from Prometheus, Loki, Tempo, and other sources.'),
('esco/skill/opentelemetry', 'OpenTelemetry', ARRAY['otel']::text[], 'Vendor-neutral observability framework for traces, metrics, and logs with SDKs, collectors, and exporters.'),
('esco/skill/datadog', 'Datadog', ARRAY[]::text[], 'SaaS observability platform unifying APM, infrastructure metrics, logs, and synthetic monitoring.'),
('esco/skill/sentry', 'Sentry', ARRAY[]::text[], 'Error and performance monitoring service with stack-trace aggregation and release tracking.'),
('esco/skill/loki', 'Grafana Loki', ARRAY['loki']::text[], 'Log aggregation system inspired by Prometheus, indexing labels rather than full log content.'),
('esco/skill/elk-stack', 'ELK Stack', ARRAY['elastic stack','elasticsearch','logstash','kibana']::text[], 'Elasticsearch + Logstash + Kibana stack for log aggregation, search, and visual analysis.'),
('esco/skill/jaeger', 'Jaeger', ARRAY[]::text[], 'Open-source distributed tracing system originally from Uber, used to inspect end-to-end request flows.'),
('esco/skill/pulumi', 'Pulumi', ARRAY[]::text[], 'Infrastructure-as-code tool that uses general-purpose languages such as TypeScript, Python, and Go.'),
('esco/skill/helm', 'Helm', ARRAY[]::text[], 'Package manager for Kubernetes that templatises and versions application release bundles called charts.'),
('esco/skill/argocd', 'Argo CD', ARRAY['gitops']::text[], 'Declarative GitOps continuous delivery tool for Kubernetes that syncs cluster state from Git.'),
('esco/skill/github-actions', 'GitHub Actions', ARRAY[]::text[], 'GitHub-hosted CI/CD platform that runs workflows defined in YAML in response to repository events.'),
('esco/skill/gitlab-ci', 'GitLab CI', ARRAY['gitlab ci/cd']::text[], 'GitLab-integrated CI/CD pipelines defined in .gitlab-ci.yml with built-in runners and registries.'),
('esco/skill/circleci', 'CircleCI', ARRAY[]::text[], 'Cloud-hosted CI/CD platform with config-as-code, parallelism, and orbs for shared pipeline logic.'),
('esco/skill/jenkins', 'Jenkins', ARRAY[]::text[], 'Self-hosted automation server with a vast plugin ecosystem and Pipeline as Code via Jenkinsfile.'),
('esco/skill/elasticsearch', 'Elasticsearch', ARRAY['elastic']::text[], 'Distributed search and analytics engine built on Lucene with full-text, aggregations, and vector search.'),
('esco/skill/clickhouse', 'ClickHouse', ARRAY[]::text[], 'Column-oriented OLAP database optimised for fast analytical queries over very large datasets.'),
('esco/skill/duckdb', 'DuckDB', ARRAY[]::text[], 'In-process column-store SQL OLAP database for fast analytics on local files and dataframes.'),
('esco/skill/cassandra', 'Apache Cassandra', ARRAY['cassandra']::text[], 'Wide-column distributed NoSQL database with tunable consistency and linear horizontal scaling.'),
('esco/skill/neo4j', 'Neo4j', ARRAY['graph database']::text[], 'Native graph database with the Cypher query language used to model relationship-heavy domains.'),
('esco/skill/snowflake', 'Snowflake', ARRAY[]::text[], 'Cloud data warehouse with separated compute and storage, supporting SQL, semi-structured data, and sharing.'),
('esco/skill/bigquery', 'BigQuery', ARRAY[]::text[], 'Google Cloud serverless data warehouse with SQL, federated queries, and built-in ML and BI engine.'),
('esco/skill/databricks', 'Databricks', ARRAY[]::text[], 'Lakehouse platform built on Apache Spark and Delta Lake for ETL, ML, and SQL analytics.'),
('esco/skill/spark', 'Apache Spark', ARRAY['pyspark']::text[], 'Distributed data processing engine for batch and streaming workloads with SQL, ML, and graph APIs.'),
('esco/skill/kafka', 'Apache Kafka', ARRAY['kafka']::text[], 'Distributed event-streaming platform used as a durable log for real-time integrations and analytics.'),
('esco/skill/airflow', 'Apache Airflow', ARRAY['airflow']::text[], 'Workflow orchestration platform for authoring, scheduling, and monitoring DAGs of data tasks.'),
('esco/skill/dbt', 'dbt', ARRAY['data build tool']::text[], 'SQL-based transformation tool that lets analysts model warehouse data with version control and testing.'),
('esco/skill/scala', 'Scala', ARRAY[]::text[], 'JVM language combining object-oriented and functional programming, used heavily in big-data and Akka systems.'),
('esco/skill/elixir', 'Elixir', ARRAY[]::text[], 'Functional, concurrent language on the BEAM VM (Erlang) used for highly concurrent fault-tolerant systems.'),
('esco/skill/zig', 'Zig', ARRAY[]::text[], 'Modern systems programming language emphasising explicit control, no hidden allocations, and C interop.'),
('esco/skill/lua', 'Lua', ARRAY[]::text[], 'Lightweight embeddable scripting language used in game engines, Redis, Neovim, and OpenResty.'),
('esco/skill/dart', 'Dart', ARRAY[]::text[], 'Client-optimised programming language used to build cross-platform Flutter applications.'),
('esco/skill/flutter', 'Flutter', ARRAY[]::text[], 'Google UI toolkit for building natively compiled mobile, web, and desktop apps from a single Dart codebase.'),
('esco/skill/ruby', 'Ruby', ARRAY[]::text[], 'Dynamic, object-oriented scripting language with elegant syntax used heavily for web back-ends.'),
('esco/skill/rails', 'Ruby on Rails', ARRAY['rails','ror']::text[], 'Convention-over-configuration MVC web framework for Ruby with ActiveRecord, ActionPack, and ActionCable.'),
('esco/skill/php', 'PHP', ARRAY[]::text[], 'Server-side scripting language for web back-ends powering WordPress, Laravel, Symfony, and Drupal.'),
('esco/skill/laravel', 'Laravel', ARRAY[]::text[], 'Expressive PHP web framework with Eloquent ORM, queues, broadcasting, and Blade templating.'),
('esco/skill/csharp', 'C#', ARRAY['c-sharp']::text[], 'Microsoft .NET object-oriented language used for back-end services, desktop apps, Unity games, and Xamarin.'),
('esco/skill/dotnet', '.NET / ASP.NET Core', ARRAY['dotnet','asp.net','asp.net core']::text[], 'Cross-platform Microsoft application framework with ASP.NET Core for web APIs and MVC.'),
('esco/skill/vitest', 'Vitest', ARRAY[]::text[], 'Vite-native unit test runner for JavaScript and TypeScript with Jest-compatible API and ESM support.'),
('esco/skill/playwright', 'Playwright', ARRAY[]::text[], 'Cross-browser end-to-end testing framework with auto-waiting, network mocking, and trace viewer.'),
('esco/skill/cypress', 'Cypress', ARRAY[]::text[], 'Front-end test runner that drives a real browser with time-travel debugging and rich DX.'),
('esco/skill/jest', 'Jest', ARRAY[]::text[], 'JavaScript testing framework with snapshot testing, mocking, and rich matchers.'),
('esco/skill/junit5', 'JUnit 5', ARRAY['junit']::text[], 'Modern JVM testing framework with extensible architecture, parameterised tests, and tag-based filtering.'),
('esco/skill/testcontainers', 'Testcontainers', ARRAY[]::text[], 'Library that runs throwaway Docker containers (Postgres, Kafka, etc.) inside integration tests.'),
('esco/skill/mockito', 'Mockito', ARRAY[]::text[], 'JVM mocking library for stubbing collaborators and verifying interactions in unit tests.'),
('esco/skill/pytest', 'pytest', ARRAY[]::text[], 'Python testing framework with fixtures, parametrisation, plugins, and rich assertion introspection.'),
('esco/skill/fastapi', 'FastAPI', ARRAY[]::text[], 'Modern Python web framework using type hints to power validation, serialisation, and OpenAPI generation.'),
('esco/skill/flask', 'Flask', ARRAY[]::text[], 'Minimal Python micro-framework for HTTP APIs and small web applications, built on Werkzeug and Jinja.'),
('esco/skill/django', 'Django', ARRAY['django rest framework','drf']::text[], 'Batteries-included Python web framework with ORM, admin, auth, and templating, plus DRF for APIs.'),
('esco/skill/nestjs', 'NestJS', ARRAY[]::text[], 'TypeScript Node.js framework using decorators and modules, modelled after Angular for back-end services.'),
('esco/skill/quarkus', 'Quarkus', ARRAY[]::text[], 'Kubernetes-native Java framework with native compilation via GraalVM and reactive programming.'),
('esco/skill/micronaut', 'Micronaut', ARRAY[]::text[], 'JVM framework with ahead-of-time compiled DI, fast startup, and low memory footprint.'),
('esco/skill/express', 'Express.js', ARRAY['express']::text[], 'Minimal Node.js web framework providing routing, middleware, and the foundation for many Node back-ends.'),
('esco/skill/oauth2', 'OAuth 2.0 / OIDC', ARRAY['oauth','openid connect','oidc']::text[], 'Standard delegated-authorization protocol with PKCE, refresh tokens, and OpenID Connect identity layer.'),
('esco/skill/keycloak', 'Keycloak', ARRAY[]::text[], 'Open-source identity and access management server with SSO, federation, and OIDC/OAuth/SAML.'),
('esco/skill/jwt', 'JSON Web Tokens', ARRAY['jwt']::text[], 'Compact signed token format used for stateless authentication and propagating identity claims.'),
('esco/skill/rabbitmq', 'RabbitMQ', ARRAY[]::text[], 'Open-source message broker implementing AMQP, used for work queues, fan-out, and RPC patterns.'),
('esco/skill/grpc', 'gRPC', ARRAY[]::text[], 'High-performance RPC framework using HTTP/2 and Protocol Buffers with streaming and code generation.'),
('esco/skill/protobuf', 'Protocol Buffers', ARRAY['protobuf','proto3']::text[], 'Schema-first binary serialisation format used to define messages and gRPC service contracts.'),
('esco/skill/graphql-server', 'GraphQL Server (Apollo / Yoga)', ARRAY['apollo server','graphql yoga']::text[], 'Server-side implementations of GraphQL exposing typed schemas over HTTP and WebSocket.'),
('esco/skill/vite', 'Vite', ARRAY[]::text[], 'Frontend build tool with native ESM dev server, lightning HMR, and Rollup-based production builds.'),
('esco/skill/webpack', 'Webpack', ARRAY[]::text[], 'JavaScript module bundler with loaders, plugins, code splitting, and tree shaking.'),
('esco/skill/storybook', 'Storybook', ARRAY[]::text[], 'UI component workshop for building, documenting, and visually testing components in isolation.'),
('esco/skill/zustand', 'Zustand', ARRAY[]::text[], 'Small unopinionated state-management library for React using hooks and a tiny store API.'),
('esco/skill/redux', 'Redux', ARRAY['redux toolkit']::text[], 'Predictable state container for JavaScript apps with actions, reducers, middleware, and dev tools.'),
('esco/skill/tanstack-query', 'TanStack Query', ARRAY['react query','tanstack-query']::text[], 'Async state library for fetching, caching, and synchronising server data in React, Vue, Solid, and Svelte.'),
('esco/skill/observability', 'Observability', ARRAY['monitoring','sli','slo']::text[], 'Discipline of understanding system behaviour through metrics, logs, traces, SLIs, and SLOs.'),
('esco/skill/sre', 'Site Reliability Engineering', ARRAY['sre']::text[], 'Engineering practice that applies software discipline to operations, with error budgets and toil reduction.'),
('esco/skill/load-testing', 'Load and Performance Testing', ARRAY['k6','jmeter','gatling']::text[], 'Designing and running load, stress, and soak tests using k6, JMeter, or Gatling against production-like systems.'),
('esco/skill/api-design', 'API Design (REST / GraphQL)', ARRAY[]::text[], 'Designing well-versioned, ergonomic, and consistent HTTP and GraphQL APIs with clear error semantics.'),
('esco/skill/event-driven', 'Event-Driven Architecture', ARRAY['eda']::text[], 'Architectural style where services communicate via asynchronous events on durable log/queue infrastructure.'),
('esco/skill/system-design', 'System Design', ARRAY['high-level design']::text[], 'Designing scalable, available, and maintainable distributed systems within explicit non-functional constraints.'),
('esco/skill/dsa-interview', 'Algorithmic Interview Preparation', ARRAY['leetcode','competitive programming']::text[], 'Pattern-based practice for typical software-engineering coding interviews — arrays, graphs, DP, intervals.'),
('esco/skill/agile', 'Agile / Scrum', ARRAY['scrum','kanban']::text[], 'Iterative software delivery practices using Scrum or Kanban with backlogs, sprints, retros, and reviews.'),
('esco/skill/code-review', 'Code Review', ARRAY[]::text[], 'Practice of reviewing and giving constructive feedback on pull requests for quality and consistency.'),
('esco/skill/technical-writing', 'Technical Writing', ARRAY['docs','documentation']::text[], 'Writing clear engineering docs, READMEs, design proposals, and runbooks for diverse internal audiences.'),
('esco/skill/clean-code', 'Clean Code & Refactoring', ARRAY['refactoring']::text[], 'Continuously refactoring code for readability and design without changing behaviour, guided by tests.'),
('esco/skill/domain-driven-design', 'Domain-Driven Design', ARRAY['ddd']::text[], 'Modelling complex business domains via aggregates, bounded contexts, ubiquitous language, and strategic patterns.');

--changeset migration:202603_16_10
insert into module_preset (id, code, name, description) values
('11111111-1111-1111-1111-000000000001', 'SE', 'Software Engineering', 'Foundational software engineering covering OOP, design patterns, testing, and version control.'),
('11111111-1111-1111-1111-000000000002', 'DSA', 'Data Structures and Algorithms', 'Classical data structures, algorithms, and complexity analysis.'),
('11111111-1111-1111-1111-000000000003', 'DB', 'Databases', 'Relational modelling, SQL, indexing, and working with PostgreSQL and Redis.'),
('11111111-1111-1111-1111-000000000004', 'WEBDEV', 'Web Development', 'Client and server development with HTML, CSS, JavaScript/TypeScript, React, Node.js, and REST APIs.'),
('11111111-1111-1111-1111-000000000005', 'ML', 'Machine Learning Fundamentals', 'Classical machine learning workflow with Python, NumPy, pandas, and scikit-learn style modelling.'),
('11111111-1111-1111-1111-000000000006', 'OS', 'Operating Systems', 'Processes, threads, concurrency primitives, memory, and low-level programming on Linux.'),
('11111111-1111-1111-1111-000000000007', 'NET', 'Computer Networks', 'TCP/IP stack, HTTP, and networking tooling on Linux.'),
('11111111-1111-1111-1111-000000000008', 'SEC', 'Computer Security', 'Applied cryptography, web application security, and authentication protocols.'),
('11111111-1111-1111-1111-000000000009', 'CLOUD', 'Cloud Basics', 'Working with public cloud (AWS), containers, and CI/CD basics.'),
('11111111-1111-1111-1111-00000000000a', 'MOB', 'Mobile Development', 'Android and iOS application development using Kotlin, Swift, and React Native.'),
('11111111-1111-1111-1111-00000000000b', 'DEVOPS', 'DevOps', 'Container orchestration, infrastructure as code, and continuous delivery pipelines.'),
('11111111-1111-1111-1111-00000000000c', 'DE', 'Data Engineering', 'SQL, Python, and pandas for cleaning, joining, and analysing data at scale.'),
('11111111-1111-1111-1111-00000000000d', 'UIUX', 'UI / UX Design', 'Designing usable, accessible web and mobile interfaces using Figma and user research.'),
('11111111-1111-1111-1111-00000000000e', 'QA', 'Software Testing and QA', 'Unit, integration, and end-to-end testing with JUnit, pytest, and Selenium.'),
('11111111-1111-1111-1111-00000000000f', 'SYS', 'Systems Design', 'Designing scalable, distributed back-end systems with microservices and caching.');

--changeset migration:202603_16_11
insert into module_skill (module_id, skill_id, proficiency) values
('11111111-1111-1111-1111-000000000001', 'esco/skill/object-oriented-programming', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000001', 'esco/skill/design-patterns', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000001', 'esco/skill/git', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000001', 'esco/skill/unit-testing', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000001', 'esco/skill/java', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000001', 'esco/skill/algorithms', 'BEGINNER'),
('11111111-1111-1111-1111-000000000001', 'esco/skill/data-structures', 'BEGINNER'),
('11111111-1111-1111-1111-000000000002', 'esco/skill/data-structures', 'ADVANCED'),
('11111111-1111-1111-1111-000000000002', 'esco/skill/algorithms', 'ADVANCED'),
('11111111-1111-1111-1111-000000000002', 'esco/skill/complexity-analysis', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000002', 'esco/skill/java', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000003', 'esco/skill/sql', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000003', 'esco/skill/postgresql', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000003', 'esco/skill/database-design', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000003', 'esco/skill/orm', 'BEGINNER'),
('11111111-1111-1111-1111-000000000003', 'esco/skill/redis', 'BEGINNER'),
('11111111-1111-1111-1111-000000000004', 'esco/skill/html', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000004', 'esco/skill/css', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000004', 'esco/skill/javascript', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000004', 'esco/skill/typescript', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000004', 'esco/skill/react', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000004', 'esco/skill/rest-api', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000004', 'esco/skill/nodejs', 'BEGINNER'),
('11111111-1111-1111-1111-000000000005', 'esco/skill/python', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000005', 'esco/skill/machine-learning', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000005', 'esco/skill/numpy', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000005', 'esco/skill/pandas', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000005', 'esco/skill/data-analysis', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000006', 'esco/skill/linux', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000006', 'esco/skill/shell-scripting', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000006', 'esco/skill/concurrency', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000006', 'esco/skill/c-plus-plus', 'BEGINNER'),
('11111111-1111-1111-1111-000000000007', 'esco/skill/tcp-ip-networking', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000007', 'esco/skill/http-protocol', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000007', 'esco/skill/linux', 'BEGINNER'),
('11111111-1111-1111-1111-000000000008', 'esco/skill/cryptography', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000008', 'esco/skill/web-security', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000008', 'esco/skill/authentication', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000008', 'esco/skill/linux', 'BEGINNER'),
('11111111-1111-1111-1111-000000000009', 'esco/skill/aws', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000009', 'esco/skill/docker', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000009', 'esco/skill/linux', 'INTERMEDIATE'),
('11111111-1111-1111-1111-000000000009', 'esco/skill/ci-cd', 'BEGINNER'),
('11111111-1111-1111-1111-00000000000a', 'esco/skill/android-development', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000a', 'esco/skill/kotlin', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000a', 'esco/skill/swift', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000a', 'esco/skill/ios-development', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000a', 'esco/skill/react-native', 'BEGINNER'),
('11111111-1111-1111-1111-00000000000b', 'esco/skill/docker', 'ADVANCED'),
('11111111-1111-1111-1111-00000000000b', 'esco/skill/kubernetes', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000b', 'esco/skill/ci-cd', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000b', 'esco/skill/terraform', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000b', 'esco/skill/linux', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000b', 'esco/skill/shell-scripting', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000c', 'esco/skill/sql', 'ADVANCED'),
('11111111-1111-1111-1111-00000000000c', 'esco/skill/python', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000c', 'esco/skill/postgresql', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000c', 'esco/skill/data-analysis', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000c', 'esco/skill/pandas', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000d', 'esco/skill/figma', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000d', 'esco/skill/user-research', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000d', 'esco/skill/accessibility', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000d', 'esco/skill/html', 'BEGINNER'),
('11111111-1111-1111-1111-00000000000d', 'esco/skill/css', 'BEGINNER'),
('11111111-1111-1111-1111-00000000000e', 'esco/skill/unit-testing', 'ADVANCED'),
('11111111-1111-1111-1111-00000000000e', 'esco/skill/integration-testing', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000e', 'esco/skill/test-driven-development', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000e', 'esco/skill/selenium', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000f', 'esco/skill/distributed-systems', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000f', 'esco/skill/microservices', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000f', 'esco/skill/rest-api', 'INTERMEDIATE'),
('11111111-1111-1111-1111-00000000000f', 'esco/skill/redis', 'BEGINNER'),
('11111111-1111-1111-1111-00000000000f', 'esco/skill/http-protocol', 'INTERMEDIATE');
